[package]
name = "vulgar-fractions"
version = "0.1.0"
authors = ["Ruben Schmidmeister <ruben.schmidmeister@icloud.com>"]
edition = "2018"
license = "MIT"

[dependencies]
fmtastic = "0.1.0"

[lib]
crate-type = ["cdylib"]
