#!/usr/bin/env bash

GENERATED_DISCLAIMER=$(cat <<EOF
// DO NOT EDIT THIS FILE. IT WAS AUTOMATICALLY GENERATED BY:
// $0

EOF
)

SINGLE_CHARACTER_FRACTIONS_FILE="src/generated/single_character_fractions.rs"

echo "$GENERATED_DISCLAIMER" > "$SINGLE_CHARACTER_FRACTIONS_FILE"
cargo run --bin generate_vulgar_fraction_lookup_fn -p codegen \
    | rustfmt \
    >> "$SINGLE_CHARACTER_FRACTIONS_FILE"
