[package]
name = "codegen"
version = "0.1.0"
authors = ["Ruben Schmidmeister <ruben.schmidmeister@icloud.com>"]
edition = "2018"
license = "MIT"

[dependencies]
syn = "1.0"
ucd-parse = "0.1"
proc-macro2 = { version = "1.0", default-features = false }
quote = "1.0"
