[package]
name = "vulgar-fractions-wasm"
version = "0.1.0"
authors = ["Ruben Schmidmeister <ruben.schmidmeister@icloud.com>"]
edition = "2018"
license = "MIT"

[dependencies]
vulgar-fractions = { path = "../../" }

[lib]
crate-type = ["cdylib"]
