name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
    - name: Build
      uses: actions-rs/cargo@v1.0.1
      with:
        command: build
        args: --all
    - name: Run tests
      uses: actions-rs/cargo@v1.0.1
      with:
        command: test
        args: --all --verbose
    - name: Run rustfmt
      uses: actions-rs/cargo@v1.0.1
      with:
        toolchain: nightly
        command: fmt
        args: --all -- --check
    - name: Run clippy
      uses: actions-rs/clippy-check@1f43527596b05bc935a41b80fad24a2117b68b2a
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        args: --all --all-features --tests
    - name: Build WASM
      run: ./scripts/build-wasm.sh
    - name: Deploy to GitHub Pages
      if: success() && github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@1230c334d1972ba00d6e3ea7c5af812f81ebcb9c
      with:
        branch: gh-pages
        folder: web/public
