name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: actions-rs/cargo@v1.0.1
      with:
        command: build
    - name: Run tests
      uses: actions-rs/cargo@v1.0.1
      with:
        command: test --verbose
    - name: Run rustfmt
      uses: actions-rs/cargo@v1.0.1
      with:
        toolchain: nightly
        command: fmt -- --check
    - name: Run clippy
      uses: actions-rs/clippy-check@v1.0.5
      with:
        token: ${secrets.GH_TOKEN}
        toolchain: nightly
        args: --all-features --tests
