name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Build
      uses: actions-rs/cargo@v1.0.1
      with:
        command: build
    - name: Run tests
      uses: actions-rs/cargo@v1.0.1
      with:
        command: test
        args: --verbose
    - name: Run rustfmt
      uses: actions-rs/cargo@v1.0.1
      with:
        toolchain: nightly
        command: fmt
        args: -- --check
    - name: Run clippy
      uses: actions-rs/clippy-check@1f43527596b05bc935a41b80fad24a2117b68b2a
      with:
        token: ${secrets.GH_TOKEN}
        # toolchain: nightly
        args: --all-features --tests
